### ISSUE TITLE
Search box buttons size on mobile viewport

### ISSUE THREAD

**Issue by philwareham** [philwareham/textpattern-hive-admin-theme#194]
Reference: https://github.com/textpattern/textpattern-default-theme/issues/200

**Comment by philwareham** [comment]
@petecooper I've actually now made the whole UI bumped to 16px on small devices - that should fix this issue (along with making text more readable to all on those devices). Closing.

**Comment by petecooper** [comment]
Do you want the Write sub-tabs (Text, HTML and Preview to increase in size for small devices, because they don't appear to at the moment.

![screen shot 2018-04-13 at 22 34 11](https://user-images.githubusercontent.com/226578/38758891-0c7348b2-3f6b-11e8-991c-839529475e50.png)

![screen shot 2018-04-13 at 22 34 23](https://user-images.githubusercontent.com/226578/38758892-0c8c201c-3f6b-11e8-92dc-f0b4de1652c8.png)

As intended or shall I raise an issue?

**Comment by philwareham** [comment]
It’s intended. I tried enlarging footnotes and other text at that size and didn’t like the space it took up.
