### ISSUE TITLE
On/off switches UI

### ISSUE THREAD

**Issue by philwareham** [philwareham/textpattern-hive-admin-theme#69]
As part of 4.7 work, I want to introduce UI that allows for on/off toggle switches, [roughly like demoed here](http://www.bootstrap-switch.org).

Only for use where it makes sense to do so (**not** on the preferences panels).

**Comment by phiw13** [comment]
Before I forget what I discussed with some windows users (one of them an IT go-to guy working for a midsize British city, who notes: very low usage amongst his users).

1. `color` and `border-color` property are set to the user default (black - `currentColor`)
2. `background-color` is painted white if specified (`transparent` is respected)
3. links are painted in the default user set color - underlining is not enforced.
4. `outline-color` is painted based on `currentColor` (e.g. blue for links, assuming blue is the color of links).
5. box-shadows are suppressed, always.
6. `opacity` is respected

[*]  the `transparent` keyword and semi-translucent colours (rgba, hsla) are converted to solid colours (black for borders in the example, white for background).

tl;dr - Open Firefox on your Mac, Preferences > Contents, click the “Colors” button, set the drop-down to “always”. Enjoy the view – this is what IE11 on Win 7, and Edge see.

Specifically for Hive: missing icons, absolutely no feedback as to focus state. For the latter, there is an easy fix: instead of using `outline: none`, use `outline: 2px solid transparent` or similar. In High-contrast mode, the outline color will be painted using the `currentColor`. Works for links and buttons or other form controls. The `#messagepane` equally has very low visibility – `border: 2px solid transparent` as an addendum helps here.

On Windows 8, as noted in previous conversation, there are couple of media queries. These can be used to load high contrast icons. It works!

```
@media (-ms-high-contrast: black-on-white) {
  .ui-icons { background-image: url(path-to-black-icons.svg) }
  .other-class, .yet-another-class, .more-class { background: url(path-to-Hive-sprite.svg); }
}
```

and ditto for white-on-black. For Firefox (which does respect the users choice of high-contrast mode) there are, as far as we could think, no easy solutions for the icons.

**Comment by philwareham** [comment]
jQuery v1.12 allows for this - will investigate benefits/drawbacks of use.

**Comment by philwareham** [comment]
FYI: On/Off example here: http://design-patterns.textpattern.io/docs/#ui-doc-jquery-ui--controlgroup

**Comment by philwareham** [comment]
May revisit this in future - not essential now.
