### ISSUE TITLE
Latest specific FF PC correction

### ISSUE THREAD

**Issue by cara-tm** [philwareham/textpattern-hive-admin-theme#99]
@Phil: I just noticed another little positioning problem with FireFox. :(

Into the "Write" panel, the selection block displaying on a click on the arrow then shown below the "Search into articles": it is moved to the left in relation to the left edge of the search input up to 6/8 pixels (due to the jQuery process).

Because I don't want to introduce too much complicated rules or CSS browser specific in your template, this simple one reduce the positioning problem. It is not perfect but divides by 2 the gap (there remains a slight subtile 3 pixels difference to the vertical of the left input edge, pretty acceptable):

    #list_control {
	position: relative;
    }

Please, first try it into your environement and if all is fine for you, you can add it into your CSS Hive themes. (Tested into "Opera developer edition" PC (latest, WebKit engine) as an alternative without any annoying visible behaviours)

Here is the actual display within FF PC (latest) without correction:

![FireFox PC latest before correction](http://imageshack.com/a/img924/5061/CGLaQa.png "FireFox PC latest before correction")

Here is the result after correction:

![FireFox PC latest after correction](http://imageshack.com/a/img921/7177/sFA6I2.png "FireFox PC latest after correction")

**Comment by philwareham** [comment]
The dropdown is positioned correctly in Mac Firefox v53, so I'm unsure why PC renders this differently. I'll keep the issue open for a couple of subsequent Firefiox releases and see if it's an actual bug in the renderer.

**Comment by phiw13** [comment]
That dropdown is positioned exactly the same (correctly) with Mac Firefox (45, 52a), Safari (9 &10), Edge (14) and Win Firefox (50.1) over here.
(tested at various window widths, so that is not the issue)

**Comment by cara-tm** [comment]
@phiw13: Are you sure (see screen shoots above)?
Could you show yours here?

**Comment by phiw13** [comment]
I’m not close to a windows box to make a screenshot right now - you’ll have to wait till tomorrow AM local time.

Just to make sure: this does **not** happen on the other list panels (Images, Files, Sections…) ?? That would be really strange, as on all those panels the search widget share the same HTML structure / CSS code (your CSS selector in the original report only applies to the Articles panel).

**Comment by phiw13** [comment]
OK, I can actually reproduce this - but I needed to create a brand new TXP4.7-dev for that. Here is interesting round of debugging:

1. The issue happens on all panels that have a search widget. Unsurprising really.

2. The issue **only** happens when there is very little content on the page (e.g. the Articles has only one or two articles, or the Files panel only lists one or two files) The key is: there must be **no** overflow on the browser window. IOW, there is no scrollbar on the window.

I found that out while playing with the developper tools, docked at the bottom of the window (this triggers overflow on the window on my Windows laptop). Took me quite a while to figure out what is going on.

To test, go to the [mock-up](http://design-patterns.textpattern.io/mockups/) site, and load the admin-log.html file (very short), or load the content-list.html file. The second one will not show the problem.

That is the reason I could not reproduce the problem at first, as my TXP47-dev test site has quite a lot of contents on every panel (enough to create overflow on every panel).

The symptom as far as I can see is that, with little content, Firefox for Windows offsets the dropdown some 10~15px to the left (the anchor point is the bottom left corner of the right most button). With more content, Firefox anchors the dropdown correctly. Hmmmm. ~15px ? That happens to be the width of the scrollbar on Windows. Hmmmm. Disabling `display: flex` on the `<body>` fixes the issue… Bug in Firefox I guess.

If anybody has access to a Linux box, it would be interesting to know if the issue happens there as well. On Mac, even if I set the scrollbars to “Always show”, I can’t reproduce it.

Perhaps setting `.txp-search` to `position: relative` minimises the issue a little (that would be the same as the original “fix“ in the OP - does’t make enough difference for my old eyes). It has no negative side effects anyway.

I suspect the problem exists in Textpattern 4.6.2 as well, but I can’t test that atm, all my sites have too much content on each panel. And nobody has complained, afaik.

**Comment by philwareham** [comment]
Thanks for investigating. I'm going to wait and see on this one. Cheers.

**Comment by cara-tm** [comment]
Phil: do not waste your time with such a little thing. Never mind, the dropdown works it's the most important.

**Comment by cara-tm** [comment]
Phil & Phiw13:

Here is the result of my investigations.
Removing the property `padding` into the rules for  the `.ui-menu` element puts the dropdown exactly in the same way within all pages (Images, Files, Sections, etc.) without the need of `position: relative`, I suggested first.


The dropdown is positioned verticaly from the right edge of the search input (perfectly), but exceed on the left (due to the rules applied to the `li` elements; which is not so ugly and maybe an honorable and simple solution).

**Comment by phiw13** [comment]
@cara-tm 

How does that fix anything? On my test install, the dropdown menu is still positioned ~15px to the left from the right edge. That is, it continues to miscalculate the `offsetLeft` positioning that is used to put it in place. (Plus, it is ugly)

When you test this, make sure there are **no** scrollbars on the window!

The only relatively *sane* solution I can think about is force a vertical scrollbar on the window – and only for Firefox.

```
@supports (-moz-appearance: none) {
    body { min-height: calc(100vh + 1px); }
}
```

BTW I can reproduce the issue with an edited version of the Jquery-ui demo for `position()` - test case [here](https://dev.l-c-n.com/_temp/jq-ui-position2.html). Now I have to get hold of the relevant Firefox people, hmm maybe next year…

**Comment by cara-tm** [comment]
Yes. Sorry, my mistake.
Your're right: this issue is due to the jQuery and its evaluation of the window's width in FF.

https://github.com/philwareham/textpattern-hive-admin-theme/issues/99#issuecomment-268951780

**Comment by phiw13** [comment]
So, an update on this, following an email conversation with one Firefox dev and because I was bored this morning.

1 - I made a really simple demo… [here](https://dev.l-c-n.com/txp/_issues/jq-ui-position.html)

In this case, the ‘bug’-trigger is having `display:flex` + `justify-content:end` set on the `.txp-search` (this mimics the Texpattern stylesheet).

Unfortunately, ‘fixing’ that won’t solve the issue globally as the upcoming `list-options` dropdown would also be affected by this Firefox bug.

STR: 

1. click the ‘click me’ button. Observe the incorrect position of the green box (right edge of square should match the right edge of the button). 
2. click again  on that button to hide, then click the Toggle Filler Content. The window should show a vertical scrollbar - reduce the height of the window if not.
3. Now click again on the ‘click me’ button. Observe that the green box is positioned correctly…

2 - Suspicion is on this really old bug: [bug 381328](https://bugzilla.mozilla.org/show_bug.cgi?id=381328), because of comments towards the bottom of the page. (via https://bugs.jquery.com/ticket/11110)

Just because I could, and I made that test case, I filed a bug: [bug 1329821](https://bugzilla.mozilla.org/show_bug.cgi?id=1329821)

3 - What to do:

1. add my ‘fix’ [mentioned above](https://github.com/philwareham/textpattern-hive-admin-theme/issues/99#issuecomment-269257516) (force a scrollbar on the window always, but only for Firefox).
2. Do nothing. If the Firefox people are not really bothered by that bug 381328, well, meh.

Option 2 is what I’ll do for Sandspaces.

**Comment by philwareham** [comment]
Thanks for investigating, Philippe. I am inclined to go for option 2 as well, since anything else is a bug hack. The widget still functions as intended even though the positing is slightly off.

**Comment by cara-tm** [comment]
Definitely, please chooses the 2 option Phil and close this issue.
Lot of thanks to Philippe for its investigations: very interesting indeed.
